### ISSUE TITLE
TopicSubscriber.java sample should minimize allocations

### ISSUE THREAD

**Issue by russellsim** [SolaceSamples/solace-samples-javarto#22]
```
public void onMessage(Handle handle) {
	try {
		// Get the received msg from the handle
		MessageSupport messageSupport = (MessageSupport) handle;
		MessageHandle rxMessage = messageSupport.getRxMessage();
		// Get the binary attachment from the msg
		ByteBuffer buffer = ByteBuffer.allocateDirect(rxMessage.getBinaryAttachmentSize()); <--- Allocate once
		rxMessage.getBinaryAttachment(buffer);
		buffer.flip();
		byte[] content = new byte[buffer.remaining()]; <--- Allocate again!
		buffer.get(content);
```

One of the features of the JavaRTO API is to minimize garbage collections for better performance.
This sample needs to be modified to reuse the highlighted objects above.

For now, a better example is RRDirectRequester.java that's bundled with the Solace API.
It properly re-uses objects to minimize allocations.

**Comment by aaron-613** [comment]
Hey Russell.  I just noticed that this issue was here.  Understood & agreed.  However, from RRDirectRequester: (should be "requestor"

```
        private ByteBuffer txContent = ByteBuffer.allocateDirect(200);
        private ByteBuffer rxContent = ByteBuffer.allocateDirect(200);
```
This very much assumes you know the payload size in advance.  I guess the author of the TopicSubscriber wanted it to work for any payload size?  I guess we could just allocate a really large buffer, or define a max size the sample can work with..?

**Comment by aaron-613** [comment]
@russellsim digging into this, trying to close off old Issues.  Apparently the way Dishant did it is correct, if you need the array of bytes.

See: https://stackoverflow.com/questions/28744096/convert-bytebuffer-to-byte-array-java

If `ByteBuffer.hasArray()` returns `false`, which it is for me, then you can't just get at the underlying array b/c there is none.  You'd have to read/parse through the ByteBuffer using `get()` methods.  Not much better option here for Strings.  I guess I can reuse the same array each time, that'll save GC.
