### ISSUE TITLE
/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java Build error

### ISSUE THREAD

**Issue by ryusatgat** [SolaceSamples/solace-samples-javarto#33]
### Bug Description

Build fail issue
need to import assert functions and change wrong variable name.

### Expected Behavior

/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:28: error: cannot find symbol
        assertNull(String.format("Expected to be passed a MessageHandle without a queue partition key, but instead "
        ^
  symbol:   method assertNull(java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:32: error: cannot find symbol
        messageHandle.setQueuePartitionKey(queueParitionKey);
                                           ^
  symbol:   variable queueParitionKey
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:33: error: cannot find symbol
        assertEquals(String.format("The configured queue partition key should have matched the specified queue partition key, "
        ^
  symbol:   method assertEquals(java.lang.String,java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:43: error: cannot find symbol
        assertNotNull(String.format("Expected to be passed a MessageHandle with a queue partition key, but instead "
        ^
  symbol:   method assertNotNull(java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:46: error: cannot find symbol
        messageHandle.setQueuePartitionKey(queueParitionKey);
                                           ^
  symbol:   variable queueParitionKey
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:47: error: cannot find symbol
        assertEquals(String.format("The configured queue partition key should have matched the specified queue partition key, "
        ^
  symbol:   method assertEquals(java.lang.String,java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:58: error: cannot find symbol
        assertNotNull(String.format("The queue partition key should not have been null."),
        ^
  symbol:   method assertNotNull(java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:67: error: cannot find symbol
        assertNull(String.format("The queue partition key should have been null, but instead was %s.",
        ^
  symbol:   method assertNull(java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:76: error: cannot find symbol
        assertNotNull(String.format("Expected to be passed a MessageHandle with a present queue partition key, but "
        ^
  symbol:   method assertNotNull(java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:80: error: cannot find symbol
        assertNull(String.format("Expected the call to `deleteQueuePartitionKey()` to succeed, causing the queue "
        ^
  symbol:   method assertNull(java.lang.String,java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
/home/ryugod/solace-samples-javarto/src/main/java/com/solace/samples/javarto/howtos/HowToUseQueuePartitionKey.java:90: error: cannot find symbol
        assertNull(String.format("Expected to be passed a MessageHandle without a queue partition key, but "
        ^
  symbol:   method assertNull(java.lang.String,java.lang.String)
  location: class com.solace.samples.javarto.snippets.HowToUseQueuePartitionKey
11 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

### Steps to Reproduce

after clone source, build with gradle.

### Solace Product

Solace PubSub+ Event Portal

### Solace API

solace-samples-javarto

### Solace API version

10.7.0

**Comment by aaron-613** [comment]
Fixed in https://github.com/SolaceSamples/solace-samples-javarto/pull/34
